id: IBEBDE880
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:08:00+00:00'
last_modified: '2022-06-07T17:33:58.154621+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19972
  title: སྟོན་པ་བདེ་བར་གཤེགས་པའི་གསུང་བསྟོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    48E8:
      image_group_id: I8LS19974
      title: ''
      total_pages: 38
      order: 1
      base_file: 48E8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
